### ISSUE TITLE
Doesn't work with released docker-py 1.5.0 (version incompatiblity)

### ISSUE THREAD

**Issue by bmenasha** [GoogleCloudPlatform/appstart#10]
This commit has the default API version of docker-py be 1.20.  

https://github.com/docker/docker-py/commit/48d72f670340b969d0e894cd6e368f76bd428bb8

This API version isn't compatible with the docker version 1.5.0 that the README claims is supported. 

Starting an app with the supported out of the box configuration results in the error:

Docker error: 500 Server Error: Internal Server Error ("Cannot start container 1dd00b564c6aaab0ebfa4703e172272559dfaea28bbf7f62949a078f9de5b1db: invalid network mode: default")

This is because docker-py will use the "default" network mode for API versions above 1.19 (and it  defaults to using api version 1.20)  yet the Docker server version 1.5.0  doesn't support this "default" network mode  (neither does 1.7.0 but I see perhaps more resent docker versions do).

Can we change the supported docker versinos to be one the latest docker-py works with? or change rquireemtns.txt t othe vreison of dcoker-p ythta owrks?

Thanks

**Comment by mindhog** [comment]
Thanks for pointing this out, [this pull request](https://github.com/GoogleCloudPlatform/appstart/pull/9) fixes the version checking to allow more recent versions of Docker.  Based on your feedback, we'll probably just increase the lowest supported version of Docker to the most recent one.

**Comment by mindhog** [comment]
(sorry, didn't mean to close)

**Comment by mindhog** [comment]
It looks like the latest docker-py only works with Docker 1.8, so I think I'm just going to make that the base supported version.

@bmenasha - work-arounds for now are to get a 1.8.x docker server and either grab the latest appstart from [PR 9](https://github.com/GoogleCloudPlatform/appstart/pull/9) or to use the --force-version option on the existing one.

**Comment by mindhog** [comment]
Now fixed in master.
