### ISSUE TITLE
Datastore is empty with every invocation

### ISSUE THREAD

**Issue by mbof** [GoogleCloudPlatform/appstart#17]
When I use appstart, the datastore is empty every time.

Inspecting the "datastore.db" file with sqlite, it seems that the data isn't deleted but each invocation creates a different app_id of the form "dev~<timestamp>", and a distinct datastore for this app_id.

**Comment by mindhog** [comment]
To persist data between invocations, you have to specify an application id, e.g.:

```
  $ appstart run --application_id=myapp app.yaml
```

Does this work for you?

**Comment by mbof** [comment]
Yes, this works -- thanks.

I would suggest not setting a timestamp as the application id if one is not given. dev_appserver's behavior seems to be using `None` as the default—wouldn't it make sense to do the same here?

If someone wants to save the data in a different data store for each invocation as with the current behavior, they could still do it by typing

```
$ appstart run --application_id=`date +%s` app.yaml
```

**Comment by mindhog** [comment]
Yeah, after thinking about it, it's kind of silly that we persist the data across runs in an inaccessible form.  We'll either revert it to the default behavior or used a default app id.
